name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: make binutils-arm-none-eabi gcc-arm-none-eabi gcc-arm-none-eabi-source libnewlib-arm-none-eabi libstdc++-arm-none-eabi-dev libstdc++-arm-none-eabi-newlib libstdc++-arm-none-eabi-picolibc picolibc-arm-none-eabi
        version: 1.0

    # - name: Install Prerequisites
    #   run: sudo apt-get install -y     - name: make
    - name: make
      working-directory: examples/debug
      run: make
